name: Publish
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true
      dry-run:
        description: 'Dry run (do not publish)'
        required: true
        type: boolean
        default: true

jobs:
  build:
    uses: ./.github/workflows/ci.yml
  publish:
    permissions:
      contents: write
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Download build artifacts
        uses: actions/download-artifact@v5
        with:
          path: ./bin
          merge-multiple: true
      - name: List files
        run: ls -la ./bin
      - name: Make binaries executable
        run: chmod +x ./bin/process-proxy-darwin-* ./bin/process-proxy-linux-*
      - name: List files
        run: ls -la ./bin
      - name: Install dependencies
        run: npm install
      - name: Build package
        run: npm run build:ts
      - name: Get author name
        id: get_author
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh api users/${{github.actor}} | jq -j .name
      - name: Set version
        env:
          GIT_AUTHOR_NAME: ${{steps.get_author.outputs.name || github.actor}}
          GIT_AUTHOR_EMAIL: ${{github.actor_id}}+${{github.actor}}@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        run: npm version ${{ github.event.inputs.version }}
      - name: Show commit
        run: git log -1
      - name: Pack package
        run: npm pack
      - name: Publish package
        if:
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish ${{ github.event.inputs['dry-run'] == true && '--dry-run' || '' }}
      - name: Publish tag
        run: git push origin --tags ${{ github.event.inputs['dry-run'] == true && '--dry-run' || '' }}
      - name: Upload package artifact
        uses: actions/upload-artifact@v5
        with:
          name: package
          path: ./*.tgz
